# Part of MKKC package
# (c) 2018 by Seo-Jin Bang, Wei Wu, and Carnegie Mellon University
# See LICENSE for licensing.

#' @title Mult-iview Simulation Data Sets
#'
#' @name multiviews
#' @aliases simAnoise simBnoise simCnoise simAredun1 simAredun2 simAredun3 simAredun4 simAredun5 simBredun1 simBredun2 simBredun3 simBredun4 simBredun5 simAredun5 simCredun1 simCredun2 simCredun3 simCredun4 simCredun5
#' @description \code{multiviews} contains multi-view simulation data used in \emph{Bang et. al (2018)}. The simulation data sets aim to describe how \code{mkkc} concatenates multiple views to extract complementary cluster information from the views with noise or redundant information.
#'
#' Each multi-view simulation data is generated by taking different combinations of four types of views: complete view, partial view 1, partial view 2, and noisy view. The complete view has complete information to distinguish the three clusters from each other. Each the partial view 1 and partial view 2 only conveys partial information so that each view alone cannot completely detect the three clusters. Partial view 1 can detect the first cluster but cannot recognize difference between the second and third clusters while Partial view 2 can detect the third cluster but cannot recognize difference between the first and second cluster. The noisy view is simply composed of noise variables which do not have any information about cluster.
#'
#' \code{simAnoise}, \code{simAredun1}, ..., \code{simAredun5} is composed of a complete view and a partial view 1. \code{simAnoise} has additional 10 noise variables to the complete view. \code{simAredun1}, ..., \code{simAredun5} have additional 5 redundant pairs to the complete view. \code{simAredun1} has the lowest level of redundancy and \code{simAredun5} has the highest level of redundancy.
#'
#' \code{simBnoise}, \code{simBredun1}, ..., \code{simBredun5} is composed of partial view 1 and partial view 2. \code{simBnoise} has additional 10 noise variables to the partial view 1. \code{simBredun1}, ..., \code{simBredun5} have additional 5 redundant pairs to the partial view 1. \code{simBredun1} has the lowest level of redundancy and \code{simBredun5} has the highest level of redundancy.
#'
#' \code{simCnoise}, \code{simCredun1}, ..., \code{simCredun5} is composed of partial view 1, partial view 2, and noisy view. \code{simCnoise} has additional 10 noise variables to the partial view 1. \code{simCredun1}, ..., \code{simCredun5} have additional 5 redundant pairs to the partial view 1. \code{simCredun1} has the lowest level of redundancy and \code{simCredun5} has the highest level of redundancy.
#'
#' For details, see \emph{Bang et. al (2018)}.
#' @docType data
#' @usage simAnoise
#' simBnoise
#' simCnoise
#' simAredun1
#' simAredun2
#' simAredun3
#' simAredun4
#' simAredun5
#' simBredun1
#' simBredun2
#' simBredun3
#' simBredun4
#' simBredun5
#' simCredun1
#' simCredun2
#' simCredun3
#' simCredun4
#' simCredun5
#' @format \code{simAnoise} is a list of three elements named \code{view1}, \code{view2}, and \code{true.label}. \code{view1} is a dataframe with 300 cases (rows) and 12 variables (columns) named \code{var1}, \code{var2}, \code{noise1}, ..., \code{noise10}. \code{view2} is a dataframe with 300 cases (rows) and 2 variables (columns) named \code{var1} and \code{var2}. \code{true.label} is a factor-type vector with three levels (100 cases for each).
#'
#' \code{simBnoise} is a list with the same format as \code{simAnoise}.
#'
#' \code{simCnoise} is a list of four elements named \code{view1}, \code{view2}, \code{view3}, and \code{true.label}. \code{view1}, \code{view2}, and \code{true.label} have the same format as \code{simAnoise}. \code{view3} is a dataframe with 300 cases (rows) and 5 variables (columns) named \code{noise1}, ..., \code{noise5}.
#'
#' \code{simAredun1}, ..., \code{simAredun5} are lists of three elements named \code{view1}, \code{view2}, and \code{true.label}. \code{view1} is a dataframe with 300 cases (rows) and 12 variables (columns) named \code{var1}, \code{var2}, \code{redun11}, \code{redun12} ..., \code{redun51}, \code{redun52}. \code{view2} is a dataframe with 300 cases (rows) and 2 variables (columns) named \code{var1} and \code{var2}. \code{true.label} is a factor-type vector with three levels (100 cases for each).
#'
#' \code{simBredun1}, ..., \code{simBredun5} are lists with the same format as \code{simAredun1}, ..., \code{simAredun5}.
#'
#' \code{simCredun1}, ..., \code{simCredun5} are lists of four elements named \code{view1}, \code{view2}, \code{view3}, and \code{true.label}. \code{view1}, \code{view2}, and \code{true.label} have the same format as \code{simAredun1}, ... \code{simAredun5}. \code{view3} is a dataframe with 300 cases (rows) and 5 variables (columns) named \code{redun11}, \code{redun12} ..., \code{redun51}, \code{redun52}.
#' @references \insertRef{bang2018mkkc}{MKKC}
#' @keywords datasets
#' @examples
#' ## visualize multi-view simulation data set A having three noise variables
#' n.noise <- 3      # number of noises to be added
#' heatmap(simAnoise$view1[,c(1:(2 + n.noise))],
#'         scale = "column", Rowv = NA, Colv = NA)     # view 1
#' heatmap(simAnoise$view2,
#'         scale = "column", Rowv = NA, Colv = NA)     # view 2
#'
#' ## visualize multi-view simulation data set B having three redundant pairs
#' n.redunpair <- 3  # number of redundant pairs to be added
#' heatmap(simBredun2$view1[,c(1:(2 + 2 * n.redunpair))],
#'         scale = "column", Rowv = NA, Colv = NA)      # view 1
#' heatmap(simBredun2$view2,
#'         scale = "column", Rowv = NA, Colv = NA)      # view 2
NULL
